package:
  name: emobpy-dev
  version: {{ environ['VERSION'] }}

source:
  path: ..

build:
  noarch_python: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  script_env:
   - VERSION
   - CONDA_BLD_PATH

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - appdirs
    - pandas
    - numpy
    - pytest
    - docopt
    - numba

test:
  imports:
    - emobpy

about:
  home: https://github.com/diw-berlin/emobpy
  license: MIT License
  summary: 'It creates vehicle driving profiles and charging availability profiles for battery electric vehicles based on mobility statistics'
license_family: MIT
